### ISSUE TITLE
Crash when message is 11 characters

### ISSUE THREAD

**Issue by DallasEpperson** [etherkit/JTEncode#10]
If `message[]` is exactly 11 characters, as in [the example sketch](https://github.com/etherkit/JTEncode/blob/436cd84/examples/Si5351JTDemo/Si5351JTDemo.ino), the library does not work. See a shorter example sketch below. This sketch _should_ simply output a single tone, and many lines of "tone change" to the serial monitor. Instead, "tone change" prints once, and the sketch stops.  

Changing `message[]` to some other string that is _not_ 11 characters results in the sketch reaching completion.
```C
#include <si5351.h>
#include <Wire.h>
#include <JTEncode.h>

Si5351 si5351;
JTEncode jtencode;

char message[] = "abababababa";
uint8_t tx_buffer[255];

unsigned long baseFreq;

void encode(){
  uint8_t i;
  memset(tx_buffer, 0, 255);
  jtencode.jt9_encode(message, tx_buffer);

  si5351.output_enable(SI5351_CLK0, 1);

  for(i = 0; i < JT9_SYMBOL_COUNT; i++){
    Serial.println("tone change");
    uint8_t test = tx_buffer[i];
    si5351.set_freq(708080000ULL, SI5351_CLK0);
    delay(580);
  }
  si5351.output_enable(SI5351_CLK0, 0);
}


void setup() {
  Serial.begin(9600);
  baseFreq = 708080000ULL;

  si5351.init(SI5351_CRYSTAL_LOAD_8PF, 0, 0);
  si5351.set_freq(baseFreq, SI5351_CLK0);
  si5351.output_enable(SI5351_CLK0, 0);
  si5351.update_status();
}

void loop() {
  delay(1000);
  Serial.println("Calling encode();");
  encode();
  Serial.println("Returned from encode();");
}
```

**Comment by NT7S** [comment]
Thank you for the bug report and the example code, excellent. I will work on reproducing it here soon.

**Comment by NT7S** [comment]
OK, I can duplicate the behavior here using an Arduino Uno. Very odd. I'll start digging into it.

**Comment by NT7S** [comment]
@DallasEpperson Looks to be a buffer problem in the code. If you can, please install the library from this tree manually and check to see if that fixes the problem for you: https://github.com/etherkit/JTEncode/tree/v1.1.2

**Comment by DallasEpperson** [comment]
Problem resolved :) I tested using the sketch above without the updated JTEncode.cpp. Then changed nothing except the contents of JTEncode.cpp, and the sketch behaves as expected.

**Comment by NT7S** [comment]
Very good. I've found a few more bugs to stamp out in a similar vein, and then I'll merge to master soon. Thanks for the feedback and testing!

**Comment by NT7S** [comment]
Made more changes to reduce RAM usage which should help the Uno and other controllers with small amounts of RAM.
