### ISSUE TITLE
Add FT8 mode

### ISSUE THREAD

**Issue by m1geo** [etherkit/JTEncode#14]
Hi Jason, any chance you will be adding FT8 to the supported modes:

http://www.arrl.org/news/new-ft8-mode-included-in-wsjt-x-beta-release

George M1GEO (y)

**Comment by NT7S** [comment]
It's definitely a possibility if I can find a whitepaper on the encoding algorithm that describes the protocol in adequate detail. If such a thing does not exist and the only way to understand the protocol is to reverse-engineer Fortran, I'd say it's not very likely. I'll look into it when I can get through some other stuff in my queue.

**Comment by frohro** [comment]
Shouldn't this issue be closed?

**Comment by m1geo** [comment]
Yup!
