### ISSUE TITLE
String overflow in jt_message_prep

### ISSUE THREAD

**Issue by mikalhart** [etherkit/JTEncode#24]
Hi!  I noticed today that in **jt_message_prep**, the code that pads a short string (less than 13 characters) with spaces overwrites the terminating null byte (undesirable).

This
```
  if(len < 13)
  {
    for(i = len; i <= 13; i++)
    {
      message[i] = ' ';
    }
  }

```
could be simply
```
  for(i = len; i < 13; i++)
  {
    message[i] = ' ';
  }
```

(Note 'i <= 13' changed to 'i < 13')

**Comment by NT7S** [comment]
Thank you, will be fixed in next release!
