### ISSUE TITLE
Hang on jtencode

### ISSUE THREAD

**Issue by michelinok** [etherkit/JTEncode#7]
Please, i'm very frustrated now...
I've started a very little project from your demo (that seems TO ME to not being working).
The problem is when i use the function 

jtencode.jt65_encode(message, tx_buffer);

It seems to stop my arduino

My code is here:

http://pastebin.com/X7bz84JB

The offending line is the n. 61

If I uncomment that line, the program/arduino hangs, instead if i comment that line everything works (ok...no jt65 good message, but i can see the carriers on the spectrum of my sdr).

PLEASE, any help is very appreciated!

**Comment by NT7S** [comment]
Yes, I have received all of your messages. I want to help everyone I can, but I am a very busy person with many demands put on me from many different sources. I will look into this when I am able to carve out a little bit of time.

**Comment by michelinok** [comment]
Hey, no problem at all!
I'm learning and probably I'll find the problem by myself in some days ☺️
Have a good weekend
'73 de IU5HES Michele


==================
Https://www.iu5hes.it
==================


Il 23 feb 2017 23:25, "Jason Milldrum" <notifications@github.com> ha
scritto:

Yes, I have received all of your messages. I want to help everyone I can,
but I am a very busy person with many demands put on me from many different
sources. I will look into this when I am able to carve out a little bit of
time.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/etherkit/JTEncode/issues/7#issuecomment-282141726>, or mute
the thread

**Comment by DallasEpperson** [comment]
The message is the culprit. Change it to `NG0CALL AA00`, for example, and your code will work just fine. 
The `N0CALL` seems to be confusing the jtencoder. I'm not entirely sure why, but I'll look into it.

**Comment by DallasEpperson** [comment]
This is strange to me. Whenever the message is 11 characters long, the `si5351.set_freq` function call freezes. 

Sample sketch:
```C
#include <si5351.h>
#include <Wire.h>
#include <JTEncode.h>

Si5351 si5351;
JTEncode jtencode;

char message[] = "abababababa";
uint8_t tx_buffer[255];

unsigned long baseFreq;

void encode(){
  uint8_t i;
  memset(tx_buffer, 0, 255);
  jtencode.jt9_encode(message, tx_buffer);

  si5351.output_enable(SI5351_CLK0, 1);

  for(i = 0; i < JT9_SYMBOL_COUNT; i++){
    Serial.println("tone change");
    uint8_t test = tx_buffer[i];
    si5351.set_freq(708080000ULL, SI5351_CLK0);
    delay(580);
  }
  si5351.output_enable(SI5351_CLK0, 0);
}


void setup() {
  Serial.begin(9600);
  baseFreq = 708080000ULL;

  si5351.init(SI5351_CRYSTAL_LOAD_8PF, 0, 0);
  si5351.set_freq(baseFreq, SI5351_CLK0);
  si5351.output_enable(SI5351_CLK0, 0);
  si5351.update_status();
}

void loop() {
  delay(1000);
  Serial.println("Calling encode();");
  encode();
  Serial.println("Returned from encode();");
}
```

**Comment by michelinok** [comment]
DallasEpperson you saved my life!
Changing the call worked perfectly.
I'll try to see if i can help you with the problem of the 11 chars as soon as i get home (12h at least)

**Comment by michelinok** [comment]
I suggest to change the callsign in the example code...just to make sure...
