### ISSUE TITLE
Incompatibility with TinyGPSPlus?

### ISSUE THREAD

**Issue by michelinok** [etherkit/JTEncode#8]
Hi!
Yes...it's me again...but this time i think the problem is very hard to investigate...
The library and my project worked ok till now...but...
If i simply add

TinyGPSPlus gpsext;

The   jtencode.jt65_encode(message, tx_buffer);    doesn't work anymore

If i remove the TinyGPSPlus declaration (i've only added the declaration!!!! and the #include <TinyGPS++.h>)   everythings works ok.

Leaving the   #include <TinyGPS++.h>    and not declaring the gpsext object, it works ok.

I've NO idea how to investigate this strange thing...the examples examples of TiniGPS++ works ok, the jtencode works ok.....but when i use  the 2 libraryes in the same project   jt65_encode(message, tx_buffer);  hangs somewhere

**Comment by michelinok** [comment]
Digging....
I've tryed switching to adafruit gps library...

When i simply add

#include <Adafruit_GPS.h>

the jt65encode won't run anymore...

so...now...no more idea :°(

**Comment by NT7S** [comment]
OK, please let me know the exact hardware you are using and please post the sketch (a link to a Gist would be preferred) you are using as well so I can attempt to replicate it here.

**Comment by michelinok** [comment]
Found the problem....
I was using the Arduino UNO R3, I've now switched to the MEGA 2560 and everything seems to work now (don't know why...but to me it seems tha the jt65 longer too much...).

Please, don't kill me now :)    I'm still a newbie with Arduino...

If you need a betatester for anything...Here i am :)

**Comment by NT7S** [comment]
I'm glad that solved your problem, but I would like the code to work on the Uno as well, so I'm not certain that I want to close this yet. Especially since I've heard of similar problems mentioned, but I haven't been able to replicate it here.

Not angry, just have a lot of demands put on my at the moment, so I can't always give responses to people as quickly as they like.

I would still like to try to replicate the problem, so if you can give me the code that was giving you trouble on the Uno I would appreciate it.

**Comment by michelinok** [comment]
sure!!!
The problem is that once i solved the problem...well....i've gone a lot far...

http://pastebin.com/NdGkr9QK

Anyway...the problem is the memory!!! Confirmed 100%!!!   i think the encode is hungry of ram...just switched without touching the code...an it works!

**Comment by michelinok** [comment]
AGAIN...thanks!!!! I know this is just an hobby!

**Comment by NT7S** [comment]
Thank you for posting it. I have suspected a RAM issue, so I'm not surprised. I'll see what I can do about getting it to work more reliably on the Uno with its limited RAM.
