### ISSUE TITLE
[Feature request] wspr_encode() - Locator 6 char

### ISSUE THREAD

**Issue by michelinok** [etherkit/JTEncode#9]
Hi!
Will you implement a 6 char locator in wspr_encode() ?

Many thanks!

PS: If you need a betatester...here I am!

**Comment by PKLoops** [comment]
Hi Jason,
It would be great to have 6 character locator in WSPR, as I would like to use a mobile WSPR transmitter for position reporting/vehicle tracking.
Many Thanks !
